package org.betaiotazeta.fractalmusicgenerator;

import java.io.InputStream;
import javax.swing.JOptionPane;
import javax.swing.text.html.HTMLEditorKit;

public class DonateDialog extends javax.swing.JDialog {

    public DonateDialog(FmgApp fmgApp, boolean modal) {
        super(fmgApp, modal);
        initComponents();
        setLocationRelativeTo(fmgApp);
        this.fmgApp = fmgApp;
        prepareDialog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donateHandshakePanel = new javax.swing.JPanel();
        handshakeLabel = new javax.swing.JLabel();
        donateScrollPane = new javax.swing.JScrollPane();
        donateEditorPane = new javax.swing.JEditorPane();
        paypalPanel = new javax.swing.JPanel();
        paypalButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Donate");

        donateHandshakePanel.setLayout(new java.awt.BorderLayout());

        handshakeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        handshakeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/betaiotazeta/fractalmusicgenerator/images/donate/handshake.png"))); // NOI18N
        donateHandshakePanel.add(handshakeLabel, java.awt.BorderLayout.CENTER);

        donateEditorPane.setFocusable(false);
        donateScrollPane.setViewportView(donateEditorPane);

        paypalPanel.setLayout(new java.awt.BorderLayout());

        paypalButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/betaiotazeta/fractalmusicgenerator/images/donate/paypal.png"))); // NOI18N
        paypalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paypalButtonActionPerformed(evt);
            }
        });
        paypalPanel.add(paypalButton, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paypalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(donateScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(donateHandshakePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(donateHandshakePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(donateScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paypalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paypalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paypalButtonActionPerformed
        try {
            String websiteUrl = "https://www.paypal.com/donate/?hosted_button_id=UFUF9GL5Q8NDL";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(websiteUrl));
        } catch (Exception ex) {
            String message = ex.getMessage();
            JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
            message = "Please, view site: https://www.paypal.com/donate/?hosted_button_id=UFUF9GL5Q8NDL";
            JOptionPane.showMessageDialog(this, message, "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_paypalButtonActionPerformed

    public void prepareDialog() {
        try {
            InputStream inputStream = getClass().getResourceAsStream("/org/betaiotazeta/fractalmusicgenerator/text/donate.html");
            donateEditorPane.setEditable(false);
            donateEditorPane.setEditorKit(new HTMLEditorKit());
            donateEditorPane.read(inputStream, null);
        } catch (Exception ex) {
            String message = ex.toString();
            JOptionPane.showMessageDialog(fmgApp, message, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane donateEditorPane;
    private javax.swing.JPanel donateHandshakePanel;
    private javax.swing.JScrollPane donateScrollPane;
    private javax.swing.JLabel handshakeLabel;
    private javax.swing.JButton paypalButton;
    private javax.swing.JPanel paypalPanel;
    // End of variables declaration//GEN-END:variables

    // Custom variables
    private String nl = System.lineSeparator();
    private FmgApp fmgApp;
}
